with open('/home/ubuntu/agendei/server/routers.ts', 'r', encoding='utf-8') as f:
    content = f.read()

old = (
    "        if (input.horaFim) updates.horaFim = input.horaFim;\n"
    "        if (input.profissionalIdPrincipal) updates.profissionalId = input.profissionalIdPrincipal;\n"
    "        await updateAgendamento(input.agendamentoId, updates);\n"
    "        // Substituir os itens\n"
    "        await deleteItensByAgendamento(input.agendamentoId);\n"
    "        // Sanitizar horaInicio/horaFim: garantir formato HH:MM (5 chars) para varchar(5)\n"
    "        const sanitizarHora = (h: string | undefined | null) => h ? h.slice(0, 5) : null;\n"
    "        await createAgendamentoItens(input.servicos.map(s => ({\n"
    "          agendamentoId: input.agendamentoId,\n"
    "          servicoId: s.servicoId,\n"
    "          profissionalId: s.profissionalId ?? null,\n"
    "          horaInicio: sanitizarHora(s.horaInicio),\n"
    "          horaFim: sanitizarHora(s.horaFim),\n"
    "          valorUnitario: s.valorUnitario,\n"
    "        })));\n"
    "        return { success: true };"
)

new = (
    "        if (input.horaFim) updates.horaFim = input.horaFim;\n"
    "        // Detectar atribuição de profissional: buscar agendamento antes de atualizar\n"
    "        const agAntes = await getAgendamentoById(input.agendamentoId);\n"
    "        const eraSemProfissional = agAntes && agAntes.profissionalId == null;\n"
    "        const novoProfissionalId = input.profissionalIdPrincipal\n"
    "          ?? input.servicos.find(s => s.profissionalId)?.profissionalId;\n"
    "        if (input.profissionalIdPrincipal) updates.profissionalId = input.profissionalIdPrincipal;\n"
    "        await updateAgendamento(input.agendamentoId, updates);\n"
    "        // Substituir os itens\n"
    "        await deleteItensByAgendamento(input.agendamentoId);\n"
    "        // Sanitizar horaInicio/horaFim: garantir formato HH:MM (5 chars) para varchar(5)\n"
    "        const sanitizarHora = (h: string | undefined | null) => h ? h.slice(0, 5) : null;\n"
    "        await createAgendamentoItens(input.servicos.map(s => ({\n"
    "          agendamentoId: input.agendamentoId,\n"
    "          servicoId: s.servicoId,\n"
    "          profissionalId: s.profissionalId ?? null,\n"
    "          horaInicio: sanitizarHora(s.horaInicio),\n"
    "          horaFim: sanitizarHora(s.horaFim),\n"
    "          valorUnitario: s.valorUnitario,\n"
    "        })));\n"
    "\n"
    "        // \u2500\u2500 Notifica\u00e7\u00e3o WhatsApp: profissional atribu\u00eddo a agendamento sem profissional \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        if (eraSemProfissional && novoProfissionalId) {\n"
    "          try {\n"
    "            const [agAtualizado, profissional] = await Promise.all([\n"
    "              getAgendamentoById(input.agendamentoId),\n"
    "              getProfissionalById(novoProfissionalId),\n"
    "            ]);\n"
    "            if (agAtualizado) {\n"
    "              const cliente = await getClienteById(agAtualizado.clienteId);\n"
    "              const telefone = cliente?.whatsapp || cliente?.telefone;\n"
    "              if (telefone && cliente) {\n"
    "                const todosServicos = await getServicosByEmpresa(empresa.id);\n"
    "                const servico = todosServicos.find(s => s.id === agAtualizado.servicoId);\n"
    "                const [ano, mes, dia] = agAtualizado.data.split('-').map(Number);\n"
    "                const dataFormatada = new Date(ano, mes - 1, dia).toLocaleDateString('pt-BR', {\n"
    "                  weekday: 'long', day: '2-digit', month: 'long'\n"
    "                });\n"
    "                const linhas: (string | null)[] = [\n"
    "                  '\U0001F4CB *Atualiza\u00e7\u00e3o do seu agendamento*',\n"
    "                  '',\n"
    "                  `Ol\u00e1, *${cliente.nome}*! Seu agendamento foi atualizado.`,\n"
    "                  '',\n"
    "                  `\U0001F4C5 *Data:* ${dataFormatada}`,\n"
    "                  `\u23F0 *Hor\u00e1rio:* ${agAtualizado.horaInicio.slice(0, 5)}`,\n"
    "                  servico ? `\u2702\uFE0F *Servi\u00e7o:* ${servico.nome}` : null,\n"
    "                  profissional ? `\U0001F464 *Profissional:* ${profissional.nome}` : null,\n"
    "                  '',\n"
    "                  `_${empresa.nome}_`,\n"
    "                ].filter(Boolean);\n"
    "                const mensagem = linhas.join('\\n');\n"
    "\n"
    "                await registrarEnvioAutomacao({\n"
    "                  empresaId: empresa.id,\n"
    "                  agendamentoId: input.agendamentoId,\n"
    "                  automacaoNome: 'Profissional Atribu\u00eddo',\n"
    "                  clienteId: cliente.id,\n"
    "                  clienteNome: cliente.nome,\n"
    "                  telefone,\n"
    "                  canal: 'whatsapp',\n"
    "                  mensagem,\n"
    "                  status: 'pendente',\n"
    "                  enviarEm: new Date(),\n"
    "                  servicoNome: servico?.nome ?? undefined,\n"
    "                });\n"
    "                console.log(`[Fila] Profissional atribu\u00eddo enfileirado para ag. ${input.agendamentoId} (${telefone})`);\n"
    "              }\n"
    "            }\n"
    "          } catch (e) {\n"
    "            console.error('[Fila] Erro ao enfileirar notifica\u00e7\u00e3o de profissional atribu\u00eddo:', e);\n"
    "          }\n"
    "        }\n"
    "\n"
    "        return { success: true };"
)

if old in content:
    content = content.replace(old, new, 1)
    with open('/home/ubuntu/agendei/server/routers.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Patch applied successfully")
else:
    print("ERROR: Target string not found")
    idx = content.find('if (input.profissionalIdPrincipal) updates.profissionalId')
    if idx >= 0:
        print(repr(content[idx-50:idx+300]))
