with open('/home/ubuntu/agendei/server/routers.ts', 'r', encoding='utf-8') as f:
    content = f.read()

old = (
    "        // \u2500\u2500 Notifica\u00e7\u00e3o WhatsApp: profissional atribu\u00eddo a agendamento sem profissional \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        if (eraSemProfissional && novoProfissionalId) {\n"
    "          try {\n"
    "            const [agAtualizado, profissional] = await Promise.all([\n"
    "              getAgendamentoById(input.agendamentoId),\n"
    "              getProfissionalById(novoProfissionalId),\n"
    "            ]);\n"
    "            if (agAtualizado) {\n"
    "              const cliente = await getClienteById(agAtualizado.clienteId);\n"
    "              const telefone = cliente?.whatsapp || cliente?.telefone;\n"
    "              if (telefone && cliente) {\n"
    "                const todosServicos = await getServicosByEmpresa(empresa.id);\n"
    "                const servico = todosServicos.find(s => s.id === agAtualizado.servicoId);\n"
    "                const [ano, mes, dia] = agAtualizado.data.split('-').map(Number);\n"
    "                const dataFormatada = new Date(ano, mes - 1, dia).toLocaleDateString('pt-BR', {\n"
    "                  weekday: 'long', day: '2-digit', month: 'long'\n"
    "                });\n"
    "                const linhas: (string | null)[] = [\n"
    "                  '\U0001F4CB *Atualiza\u00e7\u00e3o do seu agendamento*',\n"
    "                  '',\n"
    "                  `Ol\u00e1, *${cliente.nome}*! Seu agendamento foi atualizado.`,\n"
    "                  '',\n"
    "                  `\U0001F4C5 *Data:* ${dataFormatada}`,\n"
    "                  `\u23F0 *Hor\u00e1rio:* ${agAtualizado.horaInicio.slice(0, 5)}`,\n"
    "                  servico ? `\u2702\uFE0F *Servi\u00e7o:* ${servico.nome}` : null,\n"
    "                  profissional ? `\U0001F464 *Profissional:* ${profissional.nome}` : null,\n"
    "                  '',\n"
    "                  `_${empresa.nome}_`,\n"
    "                ].filter(Boolean);\n"
    "                const mensagem = linhas.join('\\n');\n"
    "                await registrarEnvioAutomacao({\n"
    "                  empresaId: empresa.id,\n"
    "                  agendamentoId: input.agendamentoId,\n"
    "                  automacaoNome: 'Profissional Atribu\u00eddo',\n"
    "                  clienteId: cliente.id,\n"
    "                  clienteNome: cliente.nome,\n"
    "                  telefone,\n"
    "                  canal: 'whatsapp',\n"
    "                  mensagem,\n"
    "                  status: 'pendente',\n"
    "                  enviarEm: new Date(),\n"
    "                  servicoNome: servico?.nome ?? undefined,\n"
    "                });\n"
    "                console.log(`[Fila] Profissional atribu\u00eddo enfileirado para ag. ${input.agendamentoId} (${telefone})`);\n"
    "              }\n"
    "            }\n"
    "          } catch (e) {\n"
    "            console.error('[Fila] Erro ao enfileirar notifica\u00e7\u00e3o de profissional atribu\u00eddo:', e);\n"
    "          }\n"
    "        }"
)

new = (
    "        // \u2500\u2500 Notifica\u00e7\u00e3o WhatsApp: profissional atribu\u00eddo a agendamento sem profissional \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\n"
    "        if (eraSemProfissional && novoProfissionalId) {\n"
    "          try {\n"
    "            const [agAtualizado, profissional] = await Promise.all([\n"
    "              getAgendamentoById(input.agendamentoId),\n"
    "              getProfissionalById(novoProfissionalId),\n"
    "            ]);\n"
    "            if (agAtualizado) {\n"
    "              const cliente = await getClienteById(agAtualizado.clienteId);\n"
    "              const telefone = cliente?.whatsapp || cliente?.telefone;\n"
    "              if (telefone && cliente) {\n"
    "                const todosServicos = await getServicosByEmpresa(empresa.id);\n"
    "                const servico = todosServicos.find(s => s.id === agAtualizado.servicoId);\n"
    "                const [ano, mes, dia] = agAtualizado.data.split('-').map(Number);\n"
    "                const dataFormatada = new Date(ano, mes - 1, dia).toLocaleDateString('pt-BR', {\n"
    "                  weekday: 'long', day: '2-digit', month: 'long'\n"
    "                });\n"
    "                // Verificar se existe automacao personalizada para este evento\n"
    "                const automacaoProfissional = await getAutomacaoByEvento(empresa.id, 'profissional_atribuido');\n"
    "                const templateVarsProfissional = {\n"
    "                  nome_cliente: cliente.nome,\n"
    "                  primeiro_nome: cliente.nome.split(' ')[0],\n"
    "                  servico: servico?.nome ?? '',\n"
    "                  data: dataFormatada,\n"
    "                  hora: `${String(agAtualizado.horaInicio ?? '').slice(0, 5)} \u2013 ${String(agAtualizado.horaFim ?? '').slice(0, 5)}`,\n"
    "                  profissional: profissional?.nome ?? '',\n"
    "                  empresa: empresa.nome,\n"
    "                  valor: `R$ ${parseFloat(String(agAtualizado.valorTotal ?? '0')).toFixed(2).replace('.', ',')}`,\n"
    "                };\n"
    "                const mensagem = automacaoProfissional?.corpoMensagem\n"
    "                  ? processarVariaveisTemplate(automacaoProfissional.corpoMensagem, templateVarsProfissional)\n"
    "                  : [\n"
    "                      '\U0001F4CB *Atualiza\u00e7\u00e3o do seu agendamento*',\n"
    "                      '',\n"
    "                      `Ol\u00e1, *${cliente.nome}*! Seu agendamento foi atualizado.`,\n"
    "                      '',\n"
    "                      `\U0001F4C5 *Data:* ${dataFormatada}`,\n"
    "                      `\u23F0 *Hor\u00e1rio:* ${agAtualizado.horaInicio.slice(0, 5)}`,\n"
    "                      servico ? `\u2702\uFE0F *Servi\u00e7o:* ${servico.nome}` : null,\n"
    "                      profissional ? `\U0001F464 *Profissional:* ${profissional.nome}` : null,\n"
    "                      '',\n"
    "                      `_${empresa.nome}_`,\n"
    "                    ].filter(Boolean).join('\\n');\n"
    "                await registrarEnvioAutomacao({\n"
    "                  empresaId: empresa.id,\n"
    "                  agendamentoId: input.agendamentoId,\n"
    "                  automacaoId: automacaoProfissional?.id,\n"
    "                  automacaoNome: automacaoProfissional?.nome ?? 'Profissional Atribu\u00eddo',\n"
    "                  clienteId: cliente.id,\n"
    "                  clienteNome: cliente.nome,\n"
    "                  telefone,\n"
    "                  canal: 'whatsapp',\n"
    "                  mensagem,\n"
    "                  status: 'pendente',\n"
    "                  enviarEm: new Date(),\n"
    "                  servicoNome: servico?.nome ?? undefined,\n"
    "                });\n"
    "                console.log(`[Fila] Profissional atribu\u00eddo enfileirado para ag. ${input.agendamentoId} (${telefone})`);\n"
    "              }\n"
    "            }\n"
    "          } catch (e) {\n"
    "            console.error('[Fila] Erro ao enfileirar notifica\u00e7\u00e3o de profissional atribu\u00eddo:', e);\n"
    "          }\n"
    "        }"
)

if old in content:
    content = content.replace(old, new, 1)
    with open('/home/ubuntu/agendei/server/routers.ts', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Patch applied successfully")
else:
    print("ERROR: Target string not found")
    idx = content.find('Profissional Atribu\u00eddo')
    if idx >= 0:
        print(repr(content[idx-100:idx+200]))
