CREATE TABLE `permissoes_individuais` (
	`id` int AUTO_INCREMENT NOT NULL,
	`profissionalId` int NOT NULL,
	`agendamentosVer` boolean,
	`agendamentosCriar` boolean,
	`agendamentosEditar` boolean,
	`agendamentosCancelar` boolean,
	`agendamentosRemarcar` boolean,
	`agendamentosConfirmar` boolean,
	`agendamentosConcluir` boolean,
	`agendamentosVerTodos` boolean,
	`clientesVer` boolean,
	`clientesCriar` boolean,
	`clientesEditar` boolean,
	`clientesExcluir` boolean,
	`clientesVerHistorico` boolean,
	`clientesVerProntuario` boolean,
	`clientesEditarProntuario` boolean,
	`clientesVerContato` boolean,
	`profissionaisVer` boolean,
	`profissionaisCriar` boolean,
	`profissionaisEditar` boolean,
	`profissionaisExcluir` boolean,
	`profissionaisGerenciarPermissoes` boolean,
	`servicosVer` boolean,
	`servicosCriar` boolean,
	`servicosEditar` boolean,
	`servicosExcluir` boolean,
	`financeiroVer` boolean,
	`financeiroVerComissoes` boolean,
	`financeiroEditarComissoes` boolean,
	`financeiroVerReceita` boolean,
	`financeiroVerCustos` boolean,
	`financeiroMarcarPago` boolean,
	`financeiroVerRelatorios` boolean,
	`agendaSolicitarBloqueio` boolean,
	`agendaAprovarBloqueio` boolean,
	`agendaVerBloqueiosTodos` boolean,
	`automacoesVer` boolean,
	`automacoesCriar` boolean,
	`automacoesEditar` boolean,
	`automacoesExcluir` boolean,
	`automacoesAtivar` boolean,
	`notificacoesVer` boolean,
	`relatoriosVer` boolean,
	`relatoriosExportar` boolean,
	`configuracoesVer` boolean,
	`configuracoesEditar` boolean,
	`usuariosVer` boolean,
	`usuariosConvidar` boolean,
	`usuariosEditar` boolean,
	`usuariosRemover` boolean,
	`gruposVer` boolean,
	`gruposCriar` boolean,
	`gruposEditar` boolean,
	`gruposExcluir` boolean,
	`dashboardVer` boolean,
	`dashboardVerMetricas` boolean,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `permissoes_individuais_id` PRIMARY KEY(`id`),
	CONSTRAINT `permissoes_individuais_profissionalId_unique` UNIQUE(`profissionalId`)
);
